#!/bin/bash

#################################
## Begin of user-editable part ##
#################################

POOL=beamv3.usa-west.nicehash.com:3387
WALLET=3AyTdh5Uvqg7aW2tPSdyTFJmpZAvqScMkx.testRun

#################################
##  End of user-editable part  ##
#################################

cd "$(dirname "$0")"

./kentot --coin BEAM --pool $POOL --user $WALLET $@
